addSbtPlugin("ch.epfl.scala"      % "sbt-version-policy"        % "2.1.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.11.0")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.5.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                   % "0.4.4")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"       % "1.9.16")
